apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz-deployment
spec:
  selector:
    matchLabels:
      app: authz
  template:
    metadata:
      labels:
        app: authz
    spec:
      containers:
        - name: authz
          image: authz:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "300Mi"
            limits:
              memory: "500Mi"
          ports:
            - containerPort: 2631
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  key: kafka-broker
                  name: backend
            - name: DOMAIN_NAME
              valueFrom:
                configMapKeyRef:
                  key: domain-name
                  name: backend
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: hostname
                  name: backend
            - name: AUTHZ
              value: "${HOSTNAME}/authz"
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  key: datasource-config.json
                  name: backend
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: jwt-secret-key
                  name: secret-keys
            - name: JAVA_TOOL_OPTIONS
              value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n'
---
apiVersion: v1
kind: Service
metadata:
  name: authz-service
spec:
  type: ClusterIP
  selector:
    app: authz
  ports:
    - name: http
      protocol: "TCP"
      port: 2631
      targetPort: 2631
    - name: grpc
      port: 3631
      targetPort: 3631
      protocol: "TCP"
