apiVersion: apps/v1
kind: Deployment # Kubernetes' resource kind we are creating
metadata:
  name: self-service-deployment
spec:
  selector:
    matchLabels:
      app: self-service
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: self-service
    spec:
      containers:
        - name: self-service
          image: self-service:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "300Mi"
            limits:
              memory: "500Mi"
          ports:
            - name: app
              containerPort: 2642
              protocol: TCP
            - name: grpc
              containerPort: 3642
              protocol: TCP
          env:
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: hostname
                  name: backend
            - name: SELF_SERVICE
              value: "${HOSTNAME}/self-services"
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  key: datasource-config.json
                  name: backend
            - name: JAVA_TOOL_OPTIONS
              value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n'
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes' resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: self-service
spec:
  selector:
    app: self-service
  ports:
    - name: http
      protocol: "TCP"
      port: 2642 # The port that the service is running on in the cluster
      targetPort: 2642 # The port exposed by the service
    - name: grpc
      protocol: "TCP"
      port: 3642 # The port that the service is running on in the cluster
      targetPort: 3642 # The port exposed by the service
  type: ClusterIP # type of the service.