apiVersion: apps/v1
kind: Deployment # Kubernetes' resource kind we are creating
metadata:
  name: call-list-deployment
spec:
  selector:
    matchLabels:
      app: call-list
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: call-list
    spec:
      containers:
        - name: call-list
          image: call-list:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "300Mi"
            limits:
              memory: "500Mi"
          ports:
            - name: app
              containerPort: 2637
              protocol: TCP
            - name: grpc
              containerPort: 3637
              protocol: TCP
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  key: kafka-broker
                  name: backend
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: hostname
                  name: backend
            - name: CALL_LIST
              value: "${HOSTNAME}/call-lists"
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  key: datasource-config.json
                  name: backend
            - name: JAVA_TOOL_OPTIONS
              value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n'
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes' resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: call-list-service
spec:
  selector:
    app: call-list
  ports:
    - name: http
      protocol: "TCP"
      port: 2637 # The port that the service is running on in the cluster
      targetPort: 2637 # The port exposed by the service
    - name: grpc
      protocol: "TCP"
      port: 3637 # The port that the service is running on in the cluster
      targetPort: 3637 # The port exposed by the service
  type: ClusterIP # type of the service.