apiVersion: apps/v1
kind: Deployment # Kubernetes' resource kind we are creating
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: inventory:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "300Mi"
            limits:
              memory: "500Mi"
          ports:
            - name: app
              containerPort: 9095
              protocol: TCP
#            - name: grpc
#              containerPort: 3635
#              protocol: TCP
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  key: kafka-broker
                  name: backend
            - name: HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: hostname
                  name: backend
            - name: INVENTORIES
              value: "${HOSTNAME}/inventories"
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  key: datasource-config.json
                  name: backend
            - name: JAVA_TOOL_OPTIONS
              value: '-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n'
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes' resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
    - name: http
      protocol: "TCP"
      port: 9095 # The port that the service is running on in the cluster
      targetPort: 9095 # The port exposed by the service
#    - name: grpc
#      protocol: "TCP"
#      port: 3635 # The port that the service is running on in the cluster
#      targetPort: 3635 # The port exposed by the service
  type: ClusterIP # type of the service.